version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: facebook_chat_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: facebook_chat_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis_cache:
    image: redis:7-alpine
    container_name: facebook_chat_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  rabbitmq_broker:
    image: rabbitmq:3-management-alpine
    container_name: facebook_chat_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

  minio_storage:
    image: minio/minio:latest
    container_name: facebook_chat_minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    environment:
      NGROK_AUTHTOKEN: 36sDGrEz255ulqdWhxdvYPd8Vsx_62tQoUceaPPsXq9QrUqBR
    command: http host.docker.internal:8000
    ports:
      - "4040:4040"
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: facebook_chat_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: facebook_chat_kibana
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    restart: always

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.0
    container_name: facebook_chat_filebeat
    user: root
    depends_on:
      - elasticsearch
    command: ["--strict.perms=false"]
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./src/pkg/logger/logs:/logs:ro
    restart: always

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  minio_data:
  elasticsearch_data: